// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: Testpage

#include "../ui.h"
#include "rtc.h"
#include <stdio.h>

lv_obj_t * ui_Homepage = NULL;
lv_obj_t * ui_Arc1 = NULL;
lv_obj_t * ui_Arc2 = NULL;
lv_obj_t * ui_Arc3 = NULL;
lv_obj_t * ui_Time = NULL;
lv_obj_t * ui_Label3 = NULL;

lv_timer_t * ui_HomepageTimer;
// event funtions

RTC_DateTypeDef GetData;  	//获取日期结构
RTC_TimeTypeDef GetTime;    //获取时间结构


static void HomePage_timer_cb(lv_timer_t* timer) {

	uint8_t timeStr[10];
	uint8_t dataStr[10];

	 /* Get the RTC current Time */
	HAL_RTC_GetTime(&hrtc, &GetTime, RTC_FORMAT_BIN);
    /* Get the RTC current Date */
    HAL_RTC_GetDate(&hrtc, &GetData, RTC_FORMAT_BIN);

    sprintf(timeStr, "%02d:%02d:%02d", GetTime.Hours, GetTime.Minutes, GetTime.Seconds);
    lv_label_set_text(ui_Time,timeStr);

    sprintf(dataStr, "20%02d/%02d/%02d", GetData.Year,GetData.Month, GetData.Date);
    lv_label_set_text(ui_Label3,dataStr);
}

// build funtions

void ui_Homepage_screen_init(void)
{
    ui_Homepage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Homepage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc1 = lv_arc_create(ui_Homepage);
    lv_obj_set_width(ui_Arc1, 210);
    lv_obj_set_height(ui_Arc1, 210);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 70);
    lv_arc_set_bg_angles(ui_Arc1, 90, 270);
    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xB8B2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xBDB2FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 12, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Arc2 = lv_arc_create(ui_Homepage);
    lv_obj_set_width(ui_Arc2, 161);
    lv_obj_set_height(ui_Arc2, 159);
    lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc2, 70);
    lv_arc_set_bg_angles(ui_Arc2, 90, 270);
    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0xB2FFF8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0xB2FFBA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc2, 12, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Arc3 = lv_arc_create(ui_Homepage);
    lv_obj_set_width(ui_Arc3, 104);
    lv_obj_set_height(ui_Arc3, 109);
    lv_obj_set_align(ui_Arc3, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc3, 70);
    lv_arc_set_bg_angles(ui_Arc3, 90, 270);
    lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0xFFD9B2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc3, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0xFFBEB2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc3, 12, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Time = lv_label_create(ui_Homepage);
    lv_obj_set_width(ui_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time, 29);
    lv_obj_set_y(ui_Time, -2);
    lv_obj_set_align(ui_Time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time, "15:30:24");
    lv_obj_set_style_text_font(ui_Time, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Homepage);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -124);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "2025/7/19");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x3EBDE9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
	
	ui_HomepageTimer = lv_timer_create(HomePage_timer_cb,500,NULL);				//0.5s刷新

}

void ui_Homepage_screen_destroy(void)
{
    if(ui_Homepage) lv_obj_del(ui_Homepage);
	lv_timer_del(ui_HomepageTimer);
    // NULL screen variables
    ui_Homepage = NULL;
    ui_Arc1 = NULL;
    ui_Arc2 = NULL;
    ui_Arc3 = NULL;
    ui_Time = NULL;
    ui_Label3 = NULL;

}
